version: '3.8'
services:
  database:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      target: 'database'
    ports:
      - '5432:5432'
    volumes:
      - pgdate:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: quests
      TZ: Asia/Tokyo
    restart: always
  api:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://admin:admin@database:5432/quests

volumes:
  pgdate:
