CREATE TABLE user_challenges
(
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users (id) DEFERRABLE INITIALLY DEFERRED,
    challenge_id TEXT NOT NULL REFERENCES challenges (id) DEFERRABLE INITIALLY DEFERRED
);