name: Check Branch History

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  check-history:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Branch History
      run: .github/workflows/check_history.sh
